/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.sasitha.springavrowebflux.domain;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class RequestHeaders extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3579415701901860280L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RequestHeaders\",\"namespace\":\"com.sasitha.springavrowebflux.domain\",\"fields\":[{\"name\":\"headers\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\",\"java-class\":\"java.util.Map\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RequestHeaders> ENCODER =
      new BinaryMessageEncoder<RequestHeaders>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RequestHeaders> DECODER =
      new BinaryMessageDecoder<RequestHeaders>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<RequestHeaders> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<RequestHeaders> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<RequestHeaders>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this RequestHeaders to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a RequestHeaders from a ByteBuffer. */
  public static RequestHeaders fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.util.Map<java.lang.String,java.lang.String> headers;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RequestHeaders() {}

  /**
   * All-args constructor.
   * @param headers The new value for headers
   */
  public RequestHeaders(java.util.Map<java.lang.String,java.lang.String> headers) {
    this.headers = headers;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return headers;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: headers = (java.util.Map<java.lang.String,java.lang.String>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'headers' field.
   * @return The value of the 'headers' field.
   */
  public java.util.Map<java.lang.String,java.lang.String> getHeaders() {
    return headers;
  }

  /**
   * Sets the value of the 'headers' field.
   * @param value the value to set.
   */
  public void setHeaders(java.util.Map<java.lang.String,java.lang.String> value) {
    this.headers = value;
  }

  /**
   * Creates a new RequestHeaders RecordBuilder.
   * @return A new RequestHeaders RecordBuilder
   */
  public static com.sasitha.springavrowebflux.domain.RequestHeaders.Builder newBuilder() {
    return new com.sasitha.springavrowebflux.domain.RequestHeaders.Builder();
  }

  /**
   * Creates a new RequestHeaders RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RequestHeaders RecordBuilder
   */
  public static com.sasitha.springavrowebflux.domain.RequestHeaders.Builder newBuilder(com.sasitha.springavrowebflux.domain.RequestHeaders.Builder other) {
    return new com.sasitha.springavrowebflux.domain.RequestHeaders.Builder(other);
  }

  /**
   * Creates a new RequestHeaders RecordBuilder by copying an existing RequestHeaders instance.
   * @param other The existing instance to copy.
   * @return A new RequestHeaders RecordBuilder
   */
  public static com.sasitha.springavrowebflux.domain.RequestHeaders.Builder newBuilder(com.sasitha.springavrowebflux.domain.RequestHeaders other) {
    return new com.sasitha.springavrowebflux.domain.RequestHeaders.Builder(other);
  }

  /**
   * RecordBuilder for RequestHeaders instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RequestHeaders>
    implements org.apache.avro.data.RecordBuilder<RequestHeaders> {

    private java.util.Map<java.lang.String,java.lang.String> headers;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.sasitha.springavrowebflux.domain.RequestHeaders.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.headers)) {
        this.headers = data().deepCopy(fields()[0].schema(), other.headers);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing RequestHeaders instance
     * @param other The existing instance to copy.
     */
    private Builder(com.sasitha.springavrowebflux.domain.RequestHeaders other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.headers)) {
        this.headers = data().deepCopy(fields()[0].schema(), other.headers);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'headers' field.
      * @return The value.
      */
    public java.util.Map<java.lang.String,java.lang.String> getHeaders() {
      return headers;
    }

    /**
      * Sets the value of the 'headers' field.
      * @param value The value of 'headers'.
      * @return This builder.
      */
    public com.sasitha.springavrowebflux.domain.RequestHeaders.Builder setHeaders(java.util.Map<java.lang.String,java.lang.String> value) {
      validate(fields()[0], value);
      this.headers = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'headers' field has been set.
      * @return True if the 'headers' field has been set, false otherwise.
      */
    public boolean hasHeaders() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'headers' field.
      * @return This builder.
      */
    public com.sasitha.springavrowebflux.domain.RequestHeaders.Builder clearHeaders() {
      headers = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RequestHeaders build() {
      try {
        RequestHeaders record = new RequestHeaders();
        record.headers = fieldSetFlags()[0] ? this.headers : (java.util.Map<java.lang.String,java.lang.String>) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RequestHeaders>
    WRITER$ = (org.apache.avro.io.DatumWriter<RequestHeaders>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RequestHeaders>
    READER$ = (org.apache.avro.io.DatumReader<RequestHeaders>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
