/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.sasitha.springavrowebflux.domain;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface StudentDomain {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"StudentDomain\",\"namespace\":\"com.sasitha.springavrowebflux.domain\",\"types\":[{\"type\":\"record\",\"name\":\"Student\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"long\",\"java-class\":\"java.lang.Long\"}},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\",\"java-class\":\"java.lang.String\"}},{\"name\":\"address\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\",\"java-class\":\"java.lang.String\"}}]},{\"type\":\"record\",\"name\":\"RequestHeaders\",\"fields\":[{\"name\":\"headers\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\",\"java-class\":\"java.util.Map\"}}]}],\"messages\":{\"saveStudent\":{\"request\":[{\"name\":\"headers\",\"type\":\"RequestHeaders\"},{\"name\":\"student\",\"type\":\"Student\"}],\"response\":\"Student\"},\"updateStudent\":{\"request\":[{\"name\":\"headers\",\"type\":\"RequestHeaders\"},{\"name\":\"student\",\"type\":\"Student\"}],\"response\":\"Student\"},\"getStudent\":{\"request\":[{\"name\":\"headers\",\"type\":\"RequestHeaders\"},{\"name\":\"id\",\"type\":\"long\"}],\"response\":\"Student\"},\"deleteStudent\":{\"request\":[{\"name\":\"headers\",\"type\":\"RequestHeaders\"},{\"name\":\"id\",\"type\":\"long\"}],\"response\":\"null\"}}}");
  /**
   */
  com.sasitha.springavrowebflux.domain.Student saveStudent(com.sasitha.springavrowebflux.domain.RequestHeaders headers, com.sasitha.springavrowebflux.domain.Student student) throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.sasitha.springavrowebflux.domain.Student updateStudent(com.sasitha.springavrowebflux.domain.RequestHeaders headers, com.sasitha.springavrowebflux.domain.Student student) throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.sasitha.springavrowebflux.domain.Student getStudent(com.sasitha.springavrowebflux.domain.RequestHeaders headers, long id) throws org.apache.avro.AvroRemoteException;
  /**
   */
  java.lang.Void deleteStudent(com.sasitha.springavrowebflux.domain.RequestHeaders headers, long id) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends StudentDomain {
    public static final org.apache.avro.Protocol PROTOCOL = com.sasitha.springavrowebflux.domain.StudentDomain.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void saveStudent(com.sasitha.springavrowebflux.domain.RequestHeaders headers, com.sasitha.springavrowebflux.domain.Student student, org.apache.avro.ipc.Callback<com.sasitha.springavrowebflux.domain.Student> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void updateStudent(com.sasitha.springavrowebflux.domain.RequestHeaders headers, com.sasitha.springavrowebflux.domain.Student student, org.apache.avro.ipc.Callback<com.sasitha.springavrowebflux.domain.Student> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getStudent(com.sasitha.springavrowebflux.domain.RequestHeaders headers, long id, org.apache.avro.ipc.Callback<com.sasitha.springavrowebflux.domain.Student> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void deleteStudent(com.sasitha.springavrowebflux.domain.RequestHeaders headers, long id, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
  }
}